[workspace]
resolver = "3"

members = ["crates/*", "services/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.98.0"

[workspace.dependencies]

# --- async/runtime ---
tokio = { version = "1.53.1", features = ["full"] }

# --- web ---
axum = { version = "0.8.9", features = ["ws", "multipart"] }

# --- serialization ---
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

# --- tracing ---
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = [
    "fmt",
    "env-filter",
    "chrono",
    "json",
] }

# --- utils ---
uuid = { version = "1.25.0", features = ["v4", "v7", "serde"] }
time = { version = "0.3.55", features = ["serde"] }
futures = "0.3.34"
bytes = "1.12.1"
image = "0.25.10"

# --- database ---
tokio-postgres = { version = "0.7.18", features = [
    "with-serde_json-1",
    "with-uuid-1",
    "with-time-0_3",
] }
deadpool-postgres = { version = "0.14.1", features = ["serde"] }

# --- auth ---
jsonwebtoken = { version = "11.0.0", features = ["default", "rust_crypto"] }
argon2 = "0.5.3"

# --- allocator ---
mimalloc = { version = "0.1.52", features = ["local_dynamic_tls"] }
