x-env: &env
  env_file:
    - .env

services:
  postgres:
    <<: *env
    image: postgres:16-alpine
    container_name: gilvave-postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    <<: *env
    image: redis:7
    container_name: gilvave-redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  rabbitmq:
    <<: *env
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # UI

volumes:
  postgres_data:
