[package]
name = "gilvave-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
uuid.workspace = true
time.workspace = true
bytes.workspace = true
axum.workspace = true
serde_json.workspace = true
tokio-postgres.workspace = true
deadpool-postgres.workspace = true
tracing.workspace = true
