[package]
name = "gilvave-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
uuid.workspace = true
validator.workspace = true
time.workspace = true
sqlx.workspace = true
bytes.workspace = true
axum.workspace = true
serde_json.workspace = true
anyhow.workspace = true
